language: ruby
rvm:
- 2.2
- 2.1
- 2.0
- 1.9.3
services:
- docker
script:
# Ansible 1.5.4 appears to be incompatible with ubuntu:16.10
- >
  wget -O- bit.ly/ansibletest | env
  DOCKER_IMAGES="ubuntu:12.04 ubuntu:14.04 ubuntu:16.04
  debian:8"
  ANSIBLE_VERSIONS="1.5.4 1.9.2 2.1.0.0" sh
- >
  wget -O- bit.ly/ansibletest | env
  DOCKER_IMAGES="ubuntu:16.10"
  ANSIBLE_VERSIONS="1.9.2 2.1.0.0" sh
after_failure:
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: H0AaCllbKXy06CEcW8qwBoZgTZ0dBkbUN+zp/ErjY3+UT2gTAz9dNpVo2DHeS5NMnpENG72p2LvnWn26N+XJxA2Tao4L1THnLEfZzzp/TTtJVgDC1aU1D1rkMoeVzwPPtSNI0Z6AreyPmPHeFX9RHdWsAXhTRJmpLiPD7QypptmYTAMRxMVJFk7ZMg/cdYS/Tbna/ASy8h8eeyxpgOg5DCk/eiMVig0v0iS97gpdULhcYPlFL/1RErYt7hCl55cThPO47bBMiP456jIFKZCcYwxp5qYQyMFyAmb3zyvDmmSbOdConMSJNzJny7XGlCKcXMH1opbHoGW652pYq6byGNwo4kvJ+7hnuF223l0Sw/Qhd8iSDmXGQcwD/y08H+Mj423jeyzkHTVY8LZ26DNVMDX/pui5JJB3bGPpL0WkJjAV0wkcXHrJSUSYnfVNw8z0kuyw6a1CoYV+2eTIYht3I25x74Msg1VH5zj2FB0utFVzGxdf72MZNlb4pc8katFdAveAEmrkUZUEmqpirFXms3IolsCdcaQ2b3AdN4IzOfkLu5oWjGikGNqsYyCQojkG5b8qMS+Xd+mQOfTSeRUNM/Xwm8w49HH//z3dEVftteCMP9EPHaXfUNStDqnSvHmZxkvluHX1CBJMHdS7ss6EcmtMkjzIk+Cz6OQ6B3Fig+M=
  email:
    recipients:
      secure: d9cf3s3a9AXbh3QMpljkfKIdL2V6okzDA8fpO2JTOIpNcKMTECIDjSsjWG8hPSmAyLT3+oTlI9pWHfndxQDgtSJ2HmVsXIM8lZcO/fNGePHBt8Pvcvd8DxtId2JXcAXHokCaYk3NUwzuttBf/Uc85Z2soCdx28BAniOEHVVj0H+Evx994qlhX32rPnrUlfa5m22FJxYb3RfiWSqvKPn4BqFsnkYJaR1MCo0tFPoXFM+gy723ag//Ch53DeVmhipxUfeRlupSxsKIRJnOxWOIE06+uHK9cbJZmrBkklFz9AnlS1LEe0BlJBh2LIn4AWdfbzvWsyR8McGMk7V7SS4MGZrU0YWMmbRI5WPmPTg4zY6sOMSzhksmAg0DcDkZ9duOxBFosq8palLss/Eo3EnREnyeNnP1JYiiTZTX2msMFGY1oXv5QBqHfv1j+iHyY38LDpm4Pfgq4xHdTG7R99ThTyX7WMm9652acsyxeTzh34MGIXourPzJHm4FbYDsdmCNVPN2wXXvIUTo7KrijJoG1mvPitlbWFGmweBcQHFhROWbNTbNvQd7pcjgly/TApv2pdvpoxja7+L6woZ8WWzA5fazKivGmbdef9fxf3o8SefvmjSo38+luHTLaE7P5vRuuOYxZ/ExIgtwRhrrqs1wfc51CbZlxlLZ/Ejxs75QmoQ=
