---
- name: add darktable key to apt-key
  apt_key: file=/root/darktable.gpg
  sudo: yes

- name: darktable sources.list
  template: src=darktable.list.j2 dest=/etc/apt/sources.list.d/darktable.list
  register: sources_list_result
  sudo: yes

- name: apt-get update
  apt: update_cache=true cache_valid_time=0
  when: sources_list_result.changed
  sudo: yes

